services:
  app:
    image: kooldev/node:20
    command: ["npm", "run", "dev"]
    ports:
      - "${KOOL_APP_PORT:-3333}:3333"
    environment:
      ASUSER: "${KOOL_ASUSER:-0}"
      UID: "${UID:-0}"
    volumes:
      - .:/app:delegated
    networks:
      - kool_local
      - kool_global
