services:
  app:
    image: kooldev/php:8.2-nginx-swoole
    command: php artisan octane:start --server=swoole --host=0.0.0.0 --port=80 --watch --poll
    ports:
      - "${KOOL_APP_PORT:-80}:80"
    environment:
      ASUSER: "${KOOL_ASUSER:-0}"
      UID: "${UID:-0}"
    volumes:
      - .:/app:delegated
    networks:
      - kool_local
      - kool_global
