services:
  app:
    image: kooldev/php:8.1-nginx
    command: php artisan octane:start --server=roadrunner --host=0.0.0.0 --rpc-port=6001 --port=80
    ports:
      - "${KOOL_APP_PORT:-80}:80"
    environment:
      ASUSER: "${KOOL_ASUSER:-0}"
      UID: "${UID:-0}"
    volumes:
      - .:/app:delegated
    networks:
      - kool_local
      - kool_global
