language: php
commands:
  create:
    - mkdir -p $CREATE_DIRECTORY/public
    - echo "<?php echo 'Hello World!';" > $CREATE_DIRECTORY/public/index.php
questions:
  compose:
    - key: app
      default_answer: PHP 7.4
      message: Which version of PHP do you want to use
      options:
        - name: PHP 7.4
          template: php74.yml
        - name: PHP 8.0
          template: php8.yml
  kool:
    - key: scripts
      default_answer: 1.x
      message: What composer version do you want to use
      options:
        - name: 1.x
          template: composer.yml
        - name: 2.x
          template: composer2.yml
templates:
  - key: scripts
    template: php.yml
