language: php
commands:
  create:
  - kool docker kooldev/php:7.4 composer create-project --prefer-dist symfony/website-skeleton
questions:
  database:
    message: What database service do you want to use
    options:
      - MySQL 8.0
      - MySQL 5.7
      - ProstgreSQL 13.0
      - none
  cache:
    message: What cache service do you want to use
    options:
      - Redis 6.0
      - Memcached 1.6
      - none

