language: javascript
commands:
  create:
    - kool docker kooldev/node:14-adonis adonis new $CREATE_DIRECTORY
questions:
  compose:
    - key: database
      default_answer: none
      message: What database service do you want to use
      options:
        - name: MySQL 8.0
          template: mysql8.yml
        - name: MySQL 5.7
          template: mysql57.yml
        - name: PostgreSQL 13.0
          template: postgresql13.yml
        - name: none
          template: none
    - key: cache
      default_answer: none
      message: What cache service do you want to use
      options:
        - name: Redis 6.0
          template: redis6.yml
        - name: Memcached 1.6
          template: memcached16.yml
        - name: none
          template: none
  kool:
    - key: scripts
      default_answer: npm
      message: What javascript package manager do you want to use
      options:
        - name: npm
          template: js-framework-npm.yml
        - name: yarn
          template: js-framework-yarn.yml
templates:
  - key: app
    template: node14-adonis.yml
  - key: scripts
    template: adonis.yml
