version: "3.8"
services:
  app:
    image: fireworkweb/node:14
    command: ["npm", "run", "dev"]
    ports:
     - "3000:3000"
    environment:
      ASUSER: "${KOOL_ASUSER:-0}"
      UID: "${UID:-0}"
    volumes:
     - .:/app:cached
     - ${HOME:-/dev/null}:/home/fwd/.ssh:cached
