# Which tags are related to this preset; used for branching the choices on preset wizard
tags: [ 'Golang' ]

name: 'CLI App'

create:
  - name: Creating new Golang CLI Application
    actions:
      - scripts:
          - mkdir -p $CREATE_DIRECTORY

# Preset defines the workflow for installing this preset in the current working directory
preset:
  - name: 'Copy basic config files'
    actions:
      - copy: kool.yml
