# Which tags are related to this preset; used for branching the choices on preset wizard
tags: [ 'TS' ]

# Create defines the workflow for creating a new Project where this preset can then be installed
create:
  - name: Creating new NestJS Application
    actions:
      - scripts:
          - docker pull -q kooldev/node:16
          - kool docker kooldev/node:16 npx -y @nestjs/cli new -l Typescript -p npm $CREATE_DIRECTORY

# Preset defines the workflow for installing this preset in the current working directory
preset:
  - name: 'Copy basic config files'
    actions:
      - copy: docker-compose.yml
      - copy: kool.yml
      - merge: docker-compose.nestjs.yml
        dst: docker-compose.yml
      - merge: kool.nestjs.yml
        dst: kool.yml
      - copy: env.dist
        dst: .env.dist

  - name: 'Customize your setup'
    actions:
      - recipe: pick-db
      - recipe: pick-cache
