services:
  app:
    image: kooldev/node:16
    command: ["npm", "run", "start:dev"]
    ports:
      - "${KOOL_APP_PORT:-3000}:${KOOL_APP_PORT:-3000}"
    environment:
      ASUSER: "${KOOL_ASUSER:-0}"
      UID: "${UID:-0}"
      KOOL_APP_PORT: "${KOOL_APP_PORT:-3000}"
    volumes:
      - .:/app:delegated
    networks:
      - kool_local
      - kool_global
