version: "3.7"
services:
  app:
    image: kooldev/node:14-nest
    command: ["npm", "run", "start:dev"]
    ports:
     - "${KOOL_APP_PORT:-3000}:3000"
    environment:
      ASUSER: "${KOOL_ASUSER:-0}"
      UID: "${UID:-0}"
    volumes:
     - .:/app:delegated
    #  - $HOME/.ssh:/home/kool/.ssh:delegated
    networks:
     - kool_local
     - kool_global
#   database:
#     image: mysql:8.0
#     ports:
#      - "${KOOL_DATABASE_PORT:-3306}:3306"
#     environment:
#       MYSQL_ROOT_PASSWORD: "${DB_PASSWORD:-rootpass}"
#       MYSQL_DATABASE: "${DB_DATABASE:-database}"
#       MYSQL_USER: "${DB_USERNAME:-user}"
#       MYSQL_PASSWORD: "${DB_PASSWORD:-pass}"
#       MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
#     volumes:
#      - db:/var/lib/mysql:delegated
#     networks:
#      - kool_local
#   cache:
#     image: redis:6-alpine
#     volumes:
#      - cache:/data:delegated
#   mongo:
#     image: mongo:4
#     ports:
#      - "${KOOL_MONGO_PORT:-27017}:27017"
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: "${MONGO_USERNAME:-root}"
#       MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD:-rootpass}"
#       MONGO_INITDB_DATABASE: "${MONGO_DATABASE:-database}"
#     volumes:
#      - mongo:/data/db:delegated
#     networks:
#      - kool_local
#
# volumes:
#   db:
#   cache:
#   mongo:

networks:
  kool_local:
  kool_global:
    external: true
    name: "${KOOL_GLOBAL_NETWORK:-kool_global}"
