# Which tags are related to this preset; used for branching the choices on preset wizard
tags: [ 'Static' ]

name: 'Hugo'

# Create defines the workflow for creating a new Project where this preset can then be installed
create:
  - name: Creating new Hugo website
    actions:
      - scripts:
          - docker pull -q klakegg/hugo:ext-alpine
          - kool docker klakegg/hugo:ext-alpine new site $CREATE_DIRECTORY

# Preset defines the workflow for installing this preset in the current working directory
preset:
  - name: 'Copy basic config files'
    actions:
      - copy: docker-compose.yml
      - copy: kool.yml
