services:
  app:
    image: klakegg/hugo
    command: ["server", "-p", "80"]
    working_dir: /app
    ports:
      - "${KOOL_APP_PORT:-80}:80"
    # environment:
    #   ASUSER: "${KOOL_ASUSER:-0}"
    #   UID: "${UID:-0}"
    volumes:
      - .:/app:delegated
    networks:
      - kool_local
      - kool_global
