services:
  node:
    image: kooldev/node:20
    command: ["npm", "run", "dev"]
    ports:
      - "3001:3001"
    volumes:
      - .:/app:delegated
    networks:
      - kool_local
      - kool_global
