services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    ports:
      - "${KOOL_DATABASE_PORT:-27017}:27017"
    environment:
      MONGODB_INITDB_ROOT_USERNAME: "${DB_USERNAME-root}"
      MONGODB_INITDB_ROOT_PASSWORD: "${DB_PASSWORD-root}"
      MONGO_INITDB_DATABASE: "${DB_DATABASE-database}"
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]

    volumes:
      - database:/data/db:delegated
    networks:
      - kool_local
      - kool_global
