services:
  database:
    image: postgres:13-alpine
    ports:
      - "${KOOL_DATABASE_PORT:-5432}:5432"
    environment:
      POSTGRES_DB: "${DB_DATABASE-database}"
      POSTGRES_USER: "${DB_USERNAME-user}"
      POSTGRES_PASSWORD: "${DB_PASSWORD-pass}"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
    - database:/var/lib/postgresql/data:delegated
    networks:
    - kool_local
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "$DB_DATABASE", "-U", "$DB_USERNAME"]

volumes:
  database:

scripts:
  psql: kool exec -e PGPASSWORD=$DB_PASSWORD database psql -U $DB_USERNAME $DB_DATABASE
