version: "3.8"
#
# Services definitions
#
services:
#
# Annonymos volumes definitions
#
volumes:
#
# Networks definitions
#
networks:
  kool_local:
  kool_global:
    external: true
    name: "${KOOL_GLOBAL_NETWORK:-kool_global}"
