# Which tags are related to this preset; used for branching the choices on preset wizard
tags: [ 'Javascript' ]

name: 'NuxtJS'

# Create defines the workflow for creating a new Project where this preset can then be installed
create:
  - name: Creating new Nuxt Application
    actions:
      - scripts:
          - docker pull -q kooldev/node:20
          - kool docker kooldev/node:20 yarn create nuxt-app $CREATE_DIRECTORY

# Preset defines the workflow for installing this preset in the current working directory
preset:
  - name: 'Copy basic config files'
    actions:
      - copy: docker-compose.yml
      - copy: kool.yml

  - name: 'Customize your setup'
    actions:
      - recipe: pick-node-pkg-mgr
