language: javascript
commands:
  create:
  - kool docker kooldev/node:14 yarn create nuxt-app $CREATE_DIRECTORY
questions:
  kool:
    - key: scripts
      default_answer: npm
      message: Which package manager did you choose during NuxtJS setup
      options:
        - name: npm
          template: npm-nuxtjs.yml
        - name: yarn
          template: yarn-nuxtjs.yml
