# Which tags are related to this preset; used for branching the choices on preset wizard
tags: [ 'JS' ]

# Create defines the workflow for creating a new Project where this preset can then be installed
create:
  - name: Creating new Laravel Application
    actions:
      - scripts:
          - mkdir $CREATE_DIRECTORY

# Preset defines the workflow for installing this preset in the current working directory
preset:
  - name: 'Copy basic config files'
    actions:
      - copy: docker-compose.yml
      - copy: kool.yml
      - copy: app.js
      - merge: node-scripts.yml
        dst: kool.yml

  - name: 'Tailor up your setup'
    actions:
      - recipe: pick-node-pkg-mgr
