# Which tags are related to this preset; used for branching the choices on preset wizard
tags: [ 'PHP' ]

name: 'CodeIgniter'

# Create defines the workflow for creating a new Project where this preset can then be installed
create:
  - name: Creating new CodeIgniter Application
    actions:
      - scripts:
          - docker pull -q kooldev/php:8.1
          - kool docker kooldev/php:8.1 composer create-project --no-install --no-scripts --prefer-dist codeigniter4/appstarter $CREATE_DIRECTORY

# Preset defines the workflow for installing this preset in the current working directory
preset:
  - name: 'Copy basic config files'
    actions:
      - copy: docker-compose.yml
      - copy: kool.yml
      - merge: codeigniter-scripts.yml
        dst: kool.yml

  - name: 'Customize your setup'
    actions:
      - recipe: pick-php
      - recipe: pick-db
      - recipe: pick-cache
      - recipe: pick-node-pkg-mgr
