name: Sync Docker Hub Description

on:
  push:
    branches:
      - master
    paths:
      - README.md
      - .github/workflows/docker-description.yml

jobs:
  docker-description:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Sync Docker Hub Description
        if: github.ref == 'refs/heads/master' && github.repository == 'kool-dev/kool'
        uses: peter-evans/dockerhub-description@v2
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          DOCKERHUB_REPOSITORY: kooldev/kool
