name: Docs Sync

on:
  push:
    tags:
      - 1.*
    paths:
      - docs/**
      - .github/workflows/docs-sync.yml
  workflow_dispatch:

jobs:
  docs-sync:
    runs-on: ubuntu-latest
    steps:
      - run: curl -fsSL http://kool.dev/sync-docs?token=$KOOL_DEV_DOCS_TOKEN
        env:
          KOOL_DEV_DOCS_TOKEN: ${{ secrets.KOOL_DEV_DOCS_TOKEN }}
