name: Docs Sync Main

on:
  workflow_dispatch:

jobs:
  docs-sync-main:
    runs-on: ubuntu-latest
    steps:
      - run: curl -fsSL "http://kool.dev/sync-docs?token=$KOOL_DEV_DOCS_TOKEN&from=main"
        env:
          KOOL_DEV_DOCS_TOKEN: ${{ secrets.KOOL_DEV_DOCS_TOKEN }}
