name: golangci-lint
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      # ref: https://github.com/golangci/golangci-lint-action/issues/442#issuecomment-1203786890
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: true
          cache-dependency-path: go.sum
      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.47.3
      - name: Run golangci-lint
        run: golangci-lint run --version --verbose --out-format=github-actions
